# Generated by Django 3.0.7 on 2020-06-08 23:04

from django.db import migrations, models
import django.db.models.deletion
import technical.lab.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.IntegerField(unique=True, verbose_name='CUIT')),
                ('tipo', models.IntegerField(choices=[(1, 'Fisica'), (2, 'Juridica')])),
            ],
        ),
        migrations.CreateModel(
            name='PersonaFisica',
            fields=[
                ('nombre', models.CharField(max_length=80, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=250, verbose_name='apellido')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('titular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='persona_fisica', serialize=False, to='lab.Titular')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('razon_social', models.CharField(max_length=100, verbose_name='razon social')),
                ('anio_fundacion', models.IntegerField(validators=[technical.lab.models.validate_anio], verbose_name='anio de fundacion')),
                ('titular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='persona_juridica', serialize=False, to='lab.Titular')),
            ],
        ),
    ]
